version: "3.8"

services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspaces:cached
        working_dir: /workspaces
        user: "root"
        init: true
        ports:
            - "3001:3001"
        command: sleep infinity
